
version: 2

sources:
    - name: staging
      #For bigquery:
      database: razor-project-339321

      # For postgres:
      # database: staging

      schema: de_final_data

      # loaded_at_field: record_loaded_at
      tables:
        - name: github_data
        - name: words_data
        # - name: yellow_tripdata
        # - name: fhv
         # freshness:
           # error_after: {count: 6, period: hour}

models:
    - name: count_data
      description: >
        Count total events
      columns:
          - name: count
            description: count
            tests:
                - unique:
                    severity: warn
                - not_null:
                    severity: warn